version: '3.8'

services:
  manager:
    build: .
    environment:
      - TOKEN=$TOKEN
      - UUID=$UUID
      - DOMAIN=$DOMAIN
      - GH_PAT=$GH_PAT
      - ALERT_WEBHOOK=$ALERT_WEBHOOK
    volumes:
      - ./control_file.txt:/app/control_file.txt
