version: '3.8'

services:
  manager:
    build: .
    environment:
      - WISP_DOMAIN=$WISP_DOMAIN
      - WISP_UUID=$WISP_UUID
      - WISP_TOKEN=$WISP_TOKEN
      - SERVER_NAME=$SERVER_NAME
      - GITHUB_PAT=$GITHUB_PAT
      - DISCORD_ALERT_WEBHOOK=$DISCORD_ALERT_WEBHOOK
      - DISCORD_FAILURE_WEBHOOK=${DISCORD_FAILURE_WEBHOOK-$DISCORD_ALERT_WEBHOOK}
      - USE_CONTROL_FILE=$USE_CONTROL_FILE
      - WISP_DEBUG=false
    env_file:
      - .env
    volumes:
      - ./control.yaml:/app/control.yaml:ro
      - ./node_modules:/app/node_modules
